// <auto-generated />
using System;
using DbStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbStorage.Migrations
{
    [DbContext(typeof(GymAppContext))]
    [Migration("20220614111915_Trainings")]
    partial class Trainings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DbStorage.DatabaseObjects.ExerciseCategoryDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCategories");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.ExerciseDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryDoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainingDoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDoId");

                    b.HasIndex("TrainingDoId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.ExerciseTrainingDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExerciseDoId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("TrainingDoId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDoId");

                    b.HasIndex("TrainingDoId");

                    b.ToTable("ExerciseTrainings");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.TrainingDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.ExerciseDo", b =>
                {
                    b.HasOne("DbStorage.DatabaseObjects.ExerciseCategoryDo", "CategoryDo")
                        .WithMany("Exercises")
                        .HasForeignKey("CategoryDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbStorage.DatabaseObjects.TrainingDo", null)
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingDoId");

                    b.Navigation("CategoryDo");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.ExerciseTrainingDo", b =>
                {
                    b.HasOne("DbStorage.DatabaseObjects.ExerciseDo", "ExerciseDo")
                        .WithMany()
                        .HasForeignKey("ExerciseDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbStorage.DatabaseObjects.TrainingDo", "TrainingDo")
                        .WithMany()
                        .HasForeignKey("TrainingDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseDo");

                    b.Navigation("TrainingDo");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.ExerciseCategoryDo", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("DbStorage.DatabaseObjects.TrainingDo", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
